apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goit-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tatiana-lapteva/lesson-8-9.git
    targetRevision: main
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true