apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: application
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 13.7.2
    helm:
      valuesObject:
        mode: standalone
        replicas: 1
        auth:
          rootUser: minio
          rootPassword: minio123
        defaultBuckets: "mlflow-artifacts"
        service:
          type: ClusterIP
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: "150m"
            memory: "128Mi"
            
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true