configs:
  cm:
    timeout.reconciliation: 180s
    accounts.devops: apiKey, login
    exec.enabled: "true"
    reposerver.exec.timeout: "300" 
  params:
    reposerver.repo.cache.expiration: 30m

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, devops, role:admin


server:
  service:
    type: ClusterIP
  extraArgs:
    - --insecure                         # ← для t3.micro

applicationSet:
  enabled: false

notifications:
  enabled: false

redis:
  enabled: true
  

dex:
  enabled: false