configs:
  cm:
    timeout.reconciliation: 180s
    accounts.devops: apiKey, login
    exec.enabled: "true"
    server.repo.server.timeout: "300" 
  params:
    reposerver.repo.cache.expiration: 30m

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, devops, role:admin


server:
  replicas: 1
  service:
    type: ClusterIP
  extraArgs:
    - --insecure                         # ← для t3.micro
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi

controller:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  extraArgs:
    - --status-processors=5
    - --operation-processors=3

repoServer:
  replicas: 1
  extraArgs:
    - --parallelismlimit=1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi   
    limits:
      cpu: 300m
      memory: 256Mi

applicationSet:
  enabled: false

notifications:
  enabled: false

redis:
  enabled: true
  master:
    persistence:
      enabled: false      
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi

dex:
  enabled: false