configs:
  cm:
    timeout.reconciliation: 30s
    accounts.devops: apiKey, login
    exec.enabled: "true"
    server.repo.server.timeout.seconds: "300" 

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, devops, role:admin


server:
  replicas: 1
  service:
    type: ClusterIP

  extraArgs:
    - --insecure                         # ← для t3.micro
  
controller:
  replicas: 1
  
# repoServer:
#   replicas: 1
#   volumes:
#     - name: helm-cache
#       emptyDir: {}
#   volumeMounts:
#     - name: helm-cache
#       mountPath: /helm/cache

repoServer:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi   
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  replicas: 1

redis:
  enabled: true

dex:
  enabled: false